services:
  web:
    image: node:22-alpine
    container_name: astro
    command: [sh, -c, "npm ci --audit=false --fund=false && npm start"]
    working_dir: /app
    ports:
      - 4321:4321
    volumes:
      - "./:/app"
